// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset.sql

package dbgen

import (
	"context"
)

const getAssetStatus = `-- name: GetAssetStatus :one
SELECT snapshot_status, readable_status FROM bookmark WHERE id = ?
`

type GetAssetStatusRow struct {
	SnapshotStatus string
	ReadableStatus string
}

func (q *Queries) GetAssetStatus(ctx context.Context, id int64) (GetAssetStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetStatus, id)
	var i GetAssetStatusRow
	err := row.Scan(&i.SnapshotStatus, &i.ReadableStatus)
	return i, err
}

const updateReadableStatus = `-- name: UpdateReadableStatus :exec
UPDATE bookmark SET readable_status = ? WHERE id = ?
`

type UpdateReadableStatusParams struct {
	ReadableStatus string
	ID             int64
}

func (q *Queries) UpdateReadableStatus(ctx context.Context, arg UpdateReadableStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReadableStatus, arg.ReadableStatus, arg.ID)
	return err
}

const updateSnapshotStatus = `-- name: UpdateSnapshotStatus :exec
UPDATE bookmark SET snapshot_status = ? WHERE id = ?
`

type UpdateSnapshotStatusParams struct {
	SnapshotStatus string
	ID             int64
}

func (q *Queries) UpdateSnapshotStatus(ctx context.Context, arg UpdateSnapshotStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSnapshotStatus, arg.SnapshotStatus, arg.ID)
	return err
}
