// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmark.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createBookmark = `-- name: CreateBookmark :execlastid
INSERT INTO bookmark (url, title, description, notes, favorite, collection_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBookmarkParams struct {
	Url          string
	Title        string
	Description  string
	Notes        string
	Favorite     int64
	CollectionID sql.NullInt64
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBookmark,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Favorite,
		arg.CollectionID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createBookmarkFull = `-- name: CreateBookmarkFull :execlastid
INSERT INTO bookmark (url, title, description, notes, archived, read, favorite, collection_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBookmarkFullParams struct {
	Url          string
	Title        string
	Description  string
	Notes        string
	Archived     int64
	Read         int64
	Favorite     int64
	CollectionID sql.NullInt64
}

func (q *Queries) CreateBookmarkFull(ctx context.Context, arg CreateBookmarkFullParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBookmarkFull,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Archived,
		arg.Read,
		arg.Favorite,
		arg.CollectionID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteBookmark = `-- name: DeleteBookmark :execresult
DELETE FROM bookmark WHERE id = ?
`

func (q *Queries) DeleteBookmark(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBookmark, id)
}

const deleteBookmarkTags = `-- name: DeleteBookmarkTags :exec
DELETE FROM bookmark_tag WHERE bookmark_id = ?
`

func (q *Queries) DeleteBookmarkTags(ctx context.Context, bookmarkID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookmarkTags, bookmarkID)
	return err
}

const getBookmark = `-- name: GetBookmark :one
SELECT id, url, title, description, notes,
       archived, read, favorite, collection_id,
       created_at, updated_at, tags,
       snapshot_status, readable_status
FROM bookmark WHERE id = ?
`

type GetBookmarkRow struct {
	ID             int64
	Url            string
	Title          string
	Description    string
	Notes          string
	Archived       int64
	Read           int64
	Favorite       int64
	CollectionID   sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
	Tags           string
	SnapshotStatus string
	ReadableStatus string
}

func (q *Queries) GetBookmark(ctx context.Context, id int64) (GetBookmarkRow, error) {
	row := q.db.QueryRowContext(ctx, getBookmark, id)
	var i GetBookmarkRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Archived,
		&i.Read,
		&i.Favorite,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.SnapshotStatus,
		&i.ReadableStatus,
	)
	return i, err
}

const getBookmarkByURL = `-- name: GetBookmarkByURL :one
SELECT id, url, title, description, notes,
       archived, read, favorite, collection_id,
       created_at, updated_at, tags,
       snapshot_status, readable_status
FROM bookmark WHERE url = ?
`

type GetBookmarkByURLRow struct {
	ID             int64
	Url            string
	Title          string
	Description    string
	Notes          string
	Archived       int64
	Read           int64
	Favorite       int64
	CollectionID   sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
	Tags           string
	SnapshotStatus string
	ReadableStatus string
}

func (q *Queries) GetBookmarkByURL(ctx context.Context, url string) (GetBookmarkByURLRow, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByURL, url)
	var i GetBookmarkByURLRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Archived,
		&i.Read,
		&i.Favorite,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.SnapshotStatus,
		&i.ReadableStatus,
	)
	return i, err
}

const getBookmarkCounts = `-- name: GetBookmarkCounts :one
SELECT
    COALESCE(SUM(CASE WHEN archived = 0 THEN 1 ELSE 0 END), 0) AS all_count,
    COALESCE(SUM(CASE WHEN favorite = 1 THEN 1 ELSE 0 END), 0) AS favorites_count,
    COALESCE(SUM(CASE WHEN read = 0    THEN 1 ELSE 0 END), 0)  AS unread_count,
    COALESCE(SUM(CASE WHEN archived = 1 THEN 1 ELSE 0 END), 0) AS archived_count
FROM bookmark
`

type GetBookmarkCountsRow struct {
	AllCount       interface{}
	FavoritesCount interface{}
	UnreadCount    interface{}
	ArchivedCount  interface{}
}

func (q *Queries) GetBookmarkCounts(ctx context.Context) (GetBookmarkCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkCounts)
	var i GetBookmarkCountsRow
	err := row.Scan(
		&i.AllCount,
		&i.FavoritesCount,
		&i.UnreadCount,
		&i.ArchivedCount,
	)
	return i, err
}

const getBookmarkURL = `-- name: GetBookmarkURL :one
SELECT url FROM bookmark WHERE id = ?
`

func (q *Queries) GetBookmarkURL(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkURL, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const updateBookmark = `-- name: UpdateBookmark :execresult
UPDATE bookmark SET url = ?, title = ?, description = ?, notes = ?, favorite = ?, collection_id = ?
WHERE id = ?
`

type UpdateBookmarkParams struct {
	Url          string
	Title        string
	Description  string
	Notes        string
	Favorite     int64
	CollectionID sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBookmark,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Favorite,
		arg.CollectionID,
		arg.ID,
	)
}
