// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collection (name, slug, color_id) VALUES (?, ?, ?)
RETURNING id, name, slug, color_id, created_at, updated_at
`

type CreateCollectionParams struct {
	Name    string
	Slug    string
	ColorID int64
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.Name, arg.Slug, arg.ColorID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :execresult
DELETE FROM collection WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCollection, id)
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, slug, color_id, created_at, updated_at
FROM collection WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ColorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, slug, color_id, created_at, updated_at
FROM collection ORDER BY name ASC
`

func (q *Queries) ListCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ColorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :execresult
UPDATE collection SET name = ?, slug = ?, color_id = ? WHERE id = ?
`

type UpdateCollectionParams struct {
	Name    string
	Slug    string
	ColorID int64
	ID      int64
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Slug,
		arg.ColorID,
		arg.ID,
	)
}
