// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favicon.sql

package dbgen

import (
	"context"
)

const getFavicon = `-- name: GetFavicon :one
SELECT data, content_type FROM favicon WHERE domain = ?
`

type GetFaviconRow struct {
	Data        []byte
	ContentType string
}

func (q *Queries) GetFavicon(ctx context.Context, domain string) (GetFaviconRow, error) {
	row := q.db.QueryRowContext(ctx, getFavicon, domain)
	var i GetFaviconRow
	err := row.Scan(&i.Data, &i.ContentType)
	return i, err
}

const getFaviconFetchedAt = `-- name: GetFaviconFetchedAt :one
SELECT fetched_at FROM favicon WHERE domain = ?
`

func (q *Queries) GetFaviconFetchedAt(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFaviconFetchedAt, domain)
	var fetched_at int64
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const upsertFavicon = `-- name: UpsertFavicon :exec
INSERT INTO favicon (domain, data, content_type, fetched_at) VALUES (?, ?, ?, unixepoch())
ON CONFLICT(domain) DO UPDATE SET data = excluded.data, content_type = excluded.content_type, fetched_at = excluded.fetched_at
`

type UpsertFaviconParams struct {
	Domain      string
	Data        []byte
	ContentType string
}

func (q *Queries) UpsertFavicon(ctx context.Context, arg UpsertFaviconParams) error {
	_, err := q.db.ExecContext(ctx, upsertFavicon, arg.Domain, arg.Data, arg.ContentType)
	return err
}

const upsertFaviconIgnore = `-- name: UpsertFaviconIgnore :exec
INSERT OR IGNORE INTO favicon (domain, data, content_type, fetched_at) VALUES (?, ?, ?, unixepoch())
`

type UpsertFaviconIgnoreParams struct {
	Domain      string
	Data        []byte
	ContentType string
}

func (q *Queries) UpsertFaviconIgnore(ctx context.Context, arg UpsertFaviconIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertFaviconIgnore, arg.Domain, arg.Data, arg.ContentType)
	return err
}
