// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlight.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createHighlight = `-- name: CreateHighlight :one
INSERT INTO highlight (bookmark_id, text, note, color, start_path, start_offset, end_path, end_offset)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, bookmark_id, text, note, color, start_path, start_offset, end_path, end_offset, created_at, updated_at
`

type CreateHighlightParams struct {
	BookmarkID  int64
	Text        string
	Note        string
	Color       string
	StartPath   string
	StartOffset int64
	EndPath     string
	EndOffset   int64
}

func (q *Queries) CreateHighlight(ctx context.Context, arg CreateHighlightParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, createHighlight,
		arg.BookmarkID,
		arg.Text,
		arg.Note,
		arg.Color,
		arg.StartPath,
		arg.StartOffset,
		arg.EndPath,
		arg.EndOffset,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.BookmarkID,
		&i.Text,
		&i.Note,
		&i.Color,
		&i.StartPath,
		&i.StartOffset,
		&i.EndPath,
		&i.EndOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHighlight = `-- name: DeleteHighlight :execresult
DELETE FROM highlight WHERE id = ?
`

func (q *Queries) DeleteHighlight(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteHighlight, id)
}

const getHighlight = `-- name: GetHighlight :one
SELECT id, bookmark_id, text, note, color, start_path, start_offset, end_path, end_offset, created_at, updated_at
FROM highlight WHERE id = ?
`

func (q *Queries) GetHighlight(ctx context.Context, id int64) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, getHighlight, id)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.BookmarkID,
		&i.Text,
		&i.Note,
		&i.Color,
		&i.StartPath,
		&i.StartOffset,
		&i.EndPath,
		&i.EndOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHighlightsByBookmark = `-- name: GetHighlightsByBookmark :many
SELECT id, bookmark_id, text, note, color, start_path, start_offset, end_path, end_offset, created_at, updated_at
FROM highlight WHERE bookmark_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetHighlightsByBookmark(ctx context.Context, bookmarkID int64) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, getHighlightsByBookmark, bookmarkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.BookmarkID,
			&i.Text,
			&i.Note,
			&i.Color,
			&i.StartPath,
			&i.StartOffset,
			&i.EndPath,
			&i.EndOffset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHighlight = `-- name: UpdateHighlight :execresult
UPDATE highlight SET note = ?, color = ? WHERE id = ?
`

type UpdateHighlightParams struct {
	Note  string
	Color string
	ID    int64
}

func (q *Queries) UpdateHighlight(ctx context.Context, arg UpdateHighlightParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateHighlight, arg.Note, arg.Color, arg.ID)
}
