// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Bookmark struct {
	ID             int64
	Url            string
	Title          string
	Description    string
	Notes          string
	Archived       int64
	Read           int64
	Favorite       int64
	CollectionID   sql.NullInt64
	Tags           string
	SnapshotStatus string
	ReadableStatus string
	CreatedAt      int64
	UpdatedAt      int64
}

type BookmarkTag struct {
	BookmarkID int64
	TagID      int64
}

type Collection struct {
	ID        int64
	Name      string
	Slug      string
	ColorID   int64
	CreatedAt int64
	UpdatedAt int64
}

type Favicon struct {
	Domain      string
	Data        []byte
	ContentType string
	FetchedAt   int64
}

type Highlight struct {
	ID          int64
	BookmarkID  int64
	Text        string
	Note        string
	Color       string
	StartPath   string
	StartOffset int64
	EndPath     string
	EndOffset   int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	Token     string
	ExpiresAt int64
}

type Tag struct {
	ID        int64
	Name      string
	Count     int64
	CreatedAt int64
	UpdatedAt int64
}
