// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package dbgen

import (
	"context"
)

const countValidSessions = `-- name: CountValidSessions :one
SELECT COUNT(*) FROM session WHERE token = ? AND expires_at > ?
`

type CountValidSessionsParams struct {
	Token     string
	ExpiresAt int64
}

func (q *Queries) CountValidSessions(ctx context.Context, arg CountValidSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidSessions, arg.Token, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO session (token, expires_at) VALUES (?, ?)
`

type CreateSessionParams struct {
	Token     string
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}
