// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package dbgen

import (
	"context"
)

const listActiveTags = `-- name: ListActiveTags :many
SELECT name, count FROM tag WHERE count > 0 ORDER BY name
`

type ListActiveTagsRow struct {
	Name  string
	Count int64
}

func (q *Queries) ListActiveTags(ctx context.Context) ([]ListActiveTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTagsRow
	for rows.Next() {
		var i ListActiveTagsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
